# Generated by Django 4.2.15 on 2024-08-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medicine_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(choices=[('surgical', 'Surgical'), ('tablet', 'Tablet'), ('syrup', 'Suryp'), ('ointment', 'Ointment')], default='tablet', max_length=100, verbose_name='Medicine Type'),
        ),
    ]
