# Generated by Django 4.2.15 on 2024-08-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_medicine_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='distributor_name',
            field=models.CharField(default='nepal', max_length=255, verbose_name='Name of distributor'),
            preserve_default=False,
        ),
    ]
