# Generated by Django 4.2.15 on 2024-08-29 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_medicine_distributor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='manufactured_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
