# Generated by Django 4.2.15 on 2024-08-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_billitem_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billitem',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='bill',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name'),
        ),
    ]
